language: elixir
elixir:
  - 1.8.0
otp_release:
  - 21.0
before_script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
script:
  - mix test
  - mix credo --strict
  - mix format --check-formatted
