language: elixir
services:
  - postgres
elixir:
  - 1.9.2
otp_release:
  - 22.1
before_script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
script:
  - mix test
  - mix credo --strict
  - mix format --check-formatted
